print("Hello world!")
name = input("Enter your name: ")
print("Hello, " + name + "!")
age = input("Enter your age: ")
age=int(age)
print(age+1)
print("You will be " + str(age+1) + "next year")
print(f"I am {age+1} next year!")